apiVersion: v1
kind: Service
metadata:
  name: {{ include "whoami.fullname" . }}
  labels:
    {{- include "whoami.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "whoami.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80