apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-stage
resources:
  - ../../base
namePrefix: stage-
commonLabels:
  env: stage
replicas:
  - name: whoami
    count: 4
images:
  - name: traefik/whoami
    newTag: v1.10.1
configMapGenerator:
  - name: whoami-env
    literals:
      - ENVIRONMENT=stage