apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-dev
resources:
  - ../../base
namePrefix: dev-
commonLabels:
  env: dev
replicas:
  - name: whoami
    count: 1
images:
  - name: traefik/whoami
    newTag: v1.10.1
configMapGenerator:
  - name: whoami-env
    literals:
      - ENVIRONMENT=dev